# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d27e8fcfe24e263dc676d037026abf7f05dbd987b0e8a1dddfc027e84252ff35c09793a90c71126186f03e6e0962011ecaa5c7c51b58b1fdf82ce77482ccb14c

test:
  secret_key_base: 24b3ca403f525139841d889c1d4435cff58ed561fbe138c1c554571d980455c00402f861757e93bd16e17f71bc63ba99a64a4b3a6153a7d9a77c4139aada19b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
